version: '3.10'

services:
  web:
    build: .
    expose:
      - 8000
    volumes:
      - .:/payment_system_stripe
      - static_volume:/payment_system_stripe/staticfiles
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/payment_system_stripe/staticfiles
    depends_on:
      - web
    networks:
      - app_network

volumes:
  static_volume:

networks:
  app_network:
